
        properties:
          order_id:
            type: number
            required: true
            example: 12345
          customer_name:
            type: string
            required: true
            example: "Laverne Brade"
          product:
            type: string
            required: true
            example: "Cheese - Brie"
          customer_address:
            type: string
            required: true
            example: "1 Pierstorff Drive"
          customer_contact:
            type: number
            required: true
            example: 7262604712
          order_type:
            type: string
            required: true
            example: "offline"
          regionOfSale:
            type: string
            required: true
            example: "New York"
          orderValue:
            type: number
            required: true
            example: 617.41